### ISSUE TITLE
Feature Request: Ability to set the letter sizing to a percentage-based value (based on size)

### ISSUE THREAD

**Issue by tfrancois** [blackpiest/letter-avatar-generator#1]
Hi, I was extremely pleased to find this great little library right when I needed to it - ironically within hours of it being posted!

Was wondering if a property/option can be set to allow the letter size to be a percentage of the total size.  For example, for an avatar of 120 pixels, perhaps having an avatar of .80 em or 80% for the height and width?  Right now the default works great, but would love to have it slightly customizable/larger.

Thanks again for sharing this nifty little tool - came in so handy and right on time!  :)

**Comment by blackpiest** [comment]
Hi! I am really glad that my library has been of help to you. I will certainly give it some thought in the days to come. 😅

**Comment by blackpiest** [comment]
Hi,

I have updated the library as you requested. You can now change the font settings.

Thanks! :)

**Comment by tfrancois** [comment]
@blackpiest : You just don't understand how time-saving and valuable this little utility is.  Thank you a million times!

EDIT:

May I suggest a fix please - (this will ensure that the letter (regardless of custom font) is always centered vertically more perfectly.  Currently, the letter is slightly off-middle depending on the font/kerning.

Replace line 50 in index.ts with the following:
`
let { actualBoundingBoxAscent, actualBoundingBoxDescent } = ctx.measureText(letter.toUpperCase());
ctx.fillText(letter.toUpperCase(), canvas.width / 2, (canvas.height / 2) + ((actualBoundingBoxAscent - actualBoundingBoxDescent) / 2) - 3);
`

P.S.: Don't ask me why that last minus 3 is necessary but it definitely is!  Thanks again!

**Comment by blackpiest** [comment]
@tfrancois, I have made the changes you requested, and I hope this will help you in your work. 

Have a great coding experience!
